
@startuml
Bob -> Alice : hello
@enduml
[Autorefresh] [Dark mode] [Change layout] [Extract window]
      Pure Javascript  PNG  SVG  ASCII Art
Discord server      
PlantUML diagram
×
×
×
×
[Home]
[What's New ?]
[Getting Started]
[Online Server]
[Running]
[F.A.Q.]
[Download]
[Forum]
[Theme]
[Preprocessing]
[Standard Library]
[Hitchhiker's Guide]
[PDF Guide]
