@startuml
package "StorageManagment" #DDDDDD{  /'songole tipologie elementi'/
class ItemFactory
{
  ItemStack getRandomItem();
  ItemStack getItem(ItemType t);
  ItemStack getItem(ItemType t, byte valore);
  ItemStack getItem(ItemType t, byte valore, byte peso);
}

class LoaderItem{
  LoaderItem(String file);
  public HashMap<ItemType, ItemStack> loadItems();
}

class ItemStack {
  String name;
  byte weight;
  byte quanty;
  byte value;
  ItemType type;   
  String description;
   
  byte getQuanity();
  void addQuantity();
  byte getPeso();
  byte getValue();
  ItemType getType();
  String getName();

  void removeQuantity();
  String showDescription();
}

enum ItemType{
  ARMA
  ARMATURA
  POZIONE_CURA
  POZIONE_DANNO
}

/'gestione di infiniti item'/
abstract Storage{   
  List<ItemStack> items = new ArrayList<ItemStack>;

  boolean add(ItemStack i);
  boolean remove(ItemStack i);
  List<ItemStack> showStorage();
  String toString();
}

class Inventario{
  byte weight;

  byte getWeight();
  byte quantyOf(ItemType t);
  ItemStack searchFor(ItemType t);
}

class Chest{
  boolean lock;
  
  void lock();
  void unlock()

}

}
Storage -> ItemStack 
Inventario --|> Storage

Chest --|> Storage
ItemStack -> ItemType




package PersistaceLayer #DDDDDD{
  class awsClient{
    void upload(File f);
    void download(String file);
    String getChecksum(String file);
  }

  class JsonParser{
    
  }
  
}

package AdapterLayer #DDDDDD{
  class AdapterSave{
    boolean checkOldSave(File f);
    File loadSave(); /'file'/
  }
}
@enduml