@startuml
class ItemFactory{
}

class ItemStack {
}

enum ItemType{
}

abstract Storage{   
}

class Inventario{
}

class Chest{

}

Storage "1" --> "n"ItemStack 
ItemStack "1" -> "1" ItemType
Inventario "1" --|> "1" Storage

Chest "1" --|> "1" Storage
ItemFactory "1" --> "n"ItemStack





  class awsClient{
  }

  class JsonParser{
    
  }
  

  class AdapterSave{

  }

class GameEngine{
 
}


class Game{

}


enum MType{
 
}

abstract class Entity{
 
} 



class Player{
}

abstract class Monster{
}
class MonsterFactory{
 
}

class xmlReader{

}

struct MonsterValues{

}


class Armatura{
 
}
class MagoNero{
  
}

class MostroMarino{
  
}
class Coboldo{
 
}
class BossDrago{
 
}


Monster "1" -->"1" MType
Player "1"--|>"1"Entity
Monster "1"--|>"1"Entity
Armatura"1"--|>"1"Monster
MagoNero"1"--|>"1"Monster
MostroMarino"1"--|>"1"Monster
Coboldo--|>"1"Monster
BossDrago"1"--|>"1"Monster

MonsterFactory"1"-->"1"BossDrago
MonsterFactory"1"-->"1"MagoNero 
MonsterFactory"1"-->"1"Coboldo
MonsterFactory"1"-->"1"Armatura
MonsterFactory"1"-->"1"MostroMarino 
MonsterFactory"1"->"1"xmlReader
xmlReader"1"->"n"MonsterValues


abstract class Menu{
  
}
class StartMenu{
 
}
class BattleMenu{

}
class MovementMenu{
 
}
struct MenuValues{

}

class GraphicAdapter{
}


BattleMenu"1"--|>"1"Menu
StartMenu"1"--|>"1"Menu
MovementMenu"1"--|>"1"Menu
Menu"1"--|>"n"MenuValues

 

    
class Coordinates{

}

class MapGraph{
 
}


enum  Direction{
 
}

class node{
  

}

class Room{

}



MapGraph"1"-->"n"Room
MapGraph"1"-->"n"node
node"1"-->"1"Coordinates
node"1"-->"4"Direction
Room"1"-->"1"Coordinates


class Prompt{

}

class Start{
 
}
class Exit{
  
}

class Showme{

}

class Showinventario{

}

class Clearconsole{

}

class Help{

}

class Back{

}

class Look{
  
}
class Attack{

}
class Move{
  
}
class Move{
  
}
class TakeFromChest{
  
}
class PlayerUse{
  
}
class RemoveItem{
  
}
class RemoveStackItem{

}
class Load{
 
}

class GameFrame{
}

interface Command{
  
}


Start"1"--|>"1"Command
Exit"1"--|>"1"Command
Look"1"--|>"1"Command
Attack"1"--|>"1"Command
Move"1"--|>"1"Command
PlayerUse"1"--|>"1"Command
RemoveItem"1"--|>"1"Command
RemoveStackItem"1"--|>"1"Command
Load"1"--|>"1"Command
Load "1"-->"1"AdapterSave
Command"1"-->"1"Save
Save"1"-->"1"AdapterSave

Load"1"->"1"GameEngine
Prompt"1"--|>"1"Command
TakeFromChest"1"--|>"1"Command

Menu"1"-->"n"Command
GameEngine"1"-->"1"Player
GameEngine"1"-->"1"MapGraph
Prompt"1"-->"1"GameEngine
Game"1"-->"1"Prompt
Player"1"-->"1"Inventario
JsonParser"1"-->"1"awsClient

AdapterSave"1"-->"1"JsonParser
GraphicAdapter"1"-->"1"GameFrame
Prompt"1"-->"1"GraphicAdapter
Command"1"-->"1"GraphicAdapter
Clearconsole"1"-->"1"GraphicAdapter
Showme"1"-->"1"Command
Showinventario"1"-->"1"Command
Help"1"-->"1"Command
Back"1"-->"1"Cammand



@enduml
