@startuml

alt INIZIALIZZAZIONE

participant Game as ga

/'---------------- INIZIALIZZAZIONE OGGETTI ----------------'/
create AdapterGrafica
ga -> AdapterGrafica: new AdapterGrafica();

create GraficaOutput
AdapterGrafica -> GraficaOutput: new GraficaOutput();

create MainMenu
ga -> MainMenu: new MainMenu();

create Prompt
ga -> Prompt : new Prompt()

create GraficaInput
Prompt -> GraficaInput : new GraficaInput();

/'create VerifyCommand
Prompt -> VerifyCommand: new VerifyCommand();
'/
end


alt AVVIO MENU INIZIALE
actor Utente as u

/'---------------- AVVIO MENU INIZIALE ----------------'/
ga -> AdapterGrafica : print(Menu.toString());
AdapterGrafica -> GraficaOutput : print(String)

ga -> Prompt : stateMenu(MainMenu);
ga -> Prompt : waitInput();
Prompt -> GraficaInput : input();

/'GraficaInput -> u'/
u -> GraficaInput : comando["start"]
GraficaInput --> Prompt : risultato di input()
Prompt --> ga : risultato di waitInput() [enum]
/'note left
Se riceve enum START allora 
si può avviare la partita
end note
'/

group Riceve comando START

/'---------------- AVVIO PARTITA ----------------'/
create GameEngine
ga -> GameEngine : new GameEngine();
create MappaGraf
GameEngine -> MappaGraf: new MappaGraf();
ga -> GameEngine : runSetup();
note right
Creazione di Player
e di mappa con nemici
item nelle stanze
end note
GameEngine -> MappaGraf : init();
ga -> MainMenu : delete[];
destroy MainMenu
create MoveMenu
ga -> MoveMenu: new MoveMenu();
ga -> Prompt : stateMenu(MoveMenu);

end
end

@enduml
